'use strict';
const assert=require('node:assert/strict'),path=require('node:path'),http=require('node:http'),fs=require('node:fs');
const {chromium}=require('playwright'),{PNG}=require('pngjs'),L=require('../src/lab-layout.js');
const root=path.join(__dirname,'..'),out=path.join(root,'artifacts','first-person-lab');
const snap=p=>p.evaluate(()=>window.labGame.snapshot());
const diff=(a,b)=>{a=PNG.sync.read(a);b=PNG.sync.read(b);let n=0;for(let i=0;i<a.data.length;i+=4)if(Math.abs(a.data[i]-b.data[i])+Math.abs(a.data[i+1]-b.data[i+1])+Math.abs(a.data[i+2]-b.data[i+2])>35)n++;return n;};
function route(start,goal){const step=.4,key=(x,z)=>`${x},${z}`,s=[Math.round(start[0]/step),Math.round(start[2]/step)],open=[s],seen=new Set([key(...s)]),parents=new Map();let found;
  for(let i=0;i<open.length;i++){const p=open[i];if(Math.hypot(p[0]*step-goal[0],p[1]*step-goal[1])<.4){found=p;break;}for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const q=[p[0]+dx,p[1]+dz],k=key(...q);if(seen.has(k)||L.blocked(q[0]*step,q[1]*step))continue;seen.add(k);parents.set(k,p);open.push(q);}}
  assert.ok(found,'BFS found route');const result=[];while(key(...found)!==key(...s)){result.unshift(found.map(v=>v*step));found=parents.get(key(...found));}result.unshift(s.map(v=>v*step));
  return result.filter((p,i)=>i===0||i===result.length-1||(p[0]-result[i-1][0])!==(result[i+1][0]-p[0])||(p[1]-result[i-1][1])!==(result[i+1][1]-p[1]));
}
async function go(p,id){const target=L.stations.find(s=>s.id===id),steps=route((await snap(p)).position,target.approach);for(const [x,z] of steps){for(const [axis,value] of [[0,x],[2,z]]){const s=await snap(p),delta=value-s.position[axis];if(Math.abs(delta)<.08)continue;const key=axis===0?(delta>0?'d':'a'):(delta>0?'s':'w');await p.keyboard.down(key);try{await p.waitForFunction(({axis,value,sign})=>(window.labGame.snapshot().position[axis]-value)*sign>-.045,{axis,value,sign:Math.sign(delta)},{timeout:15000});}finally{await p.keyboard.up(key);}}}assert.equal((await snap(p)).nearStation,id);assert.equal((await snap(p)).mode,'walk','approaching must not auto-open');await p.locator('#interact').click();}
async function steer(p){const r=await p.locator('#joystick').boundingBox(),x=r.x+r.width/2,y=r.y+r.height/2;await p.mouse.move(x,y);await p.mouse.down();await p.mouse.move(x+r.width*.29,y,{steps:4});await p.waitForTimeout(450);await p.mouse.up();}
async function distance(p,value){await p.locator('#bench-distance').evaluate((el,v)=>{el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}));},value);}
async function inside(p,selectors){const data=await p.evaluate(selectors=>{const game=document.querySelector('#game').getBoundingClientRect();return {ratio:game.width/game.height,scroll:document.documentElement.scrollWidth>innerWidth||document.documentElement.scrollHeight>innerHeight,controls:selectors.map(sel=>{const r=document.querySelector(sel).getBoundingClientRect();return {sel,ok:r.width>=1&&r.height>=1&&r.left>=game.left-1&&r.right<=game.right+1&&r.top>=game.top-1&&r.bottom<=game.bottom+1};})};},selectors);assert.ok(Math.abs(data.ratio-16/9)<.001);assert.equal(data.scroll,false);for(const c of data.controls)assert.ok(c.ok,c.sel+' stays in 16:9 game');}
(async()=>{fs.mkdirSync(out,{recursive:true});const server=http.createServer((req,res)=>{let url=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(url==='/')url='/electricity_lab_first_person.html';const file=path.resolve(root,'.'+url);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'application/octet-stream');res.end(data);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const errors=[];
try{browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const url=`http://127.0.0.1:${server.address().port}/electricity_lab_first_person.html`,p=await browser.newPage({viewport:{width:1440,height:900}}),requests=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>requests.push(r.url()));await p.goto(url);await p.waitForFunction(()=>window.labGame?.snapshot().environmentStatus==='ready');assert.equal((await snap(p)).characterDownloaded,false);assert.equal(requests.some(x=>/march-walk|catalog.json/.test(x)),false);await inside(p,['#joystick','#interact','#map-button','#look-left','#look-right']);await p.locator('#game').screenshot({path:path.join(out,'game-entry.png')});
await go(p,'scope');assert.equal((await snap(p)).mode,'lab');await inside(p,['#joystick','#bench-ground','#bench-leave','#bench-rod-positive']);
await distance(p,100);const before=await p.locator('#world').screenshot();assert.ok((await snap(p)).benchFlowVisible>0);await p.waitForTimeout(1050);const after=await p.locator('#world').screenshot();assert.ok(diff(before,after)>20,'electroscope canvas really animates');await p.locator('[data-scope-answer="neutral"]').click();assert.deepEqual((await snap(p)).completed,[1]);await p.locator('#bench-ground').click();await p.locator('#bench-ground').click();await distance(p,0);await p.locator('[data-scope-answer="positive"]').click();assert.deepEqual((await snap(p)).completed,[1,2]);await p.locator('#game').screenshot({path:path.join(out,'game-scope.png')});await p.locator('#bench-leave').click();
await go(p,'friction');await p.locator('#friction-predict-tool').click();for(let n=0;n<4;n++){await p.locator('#friction-rub-key').click();await p.waitForTimeout(900);}assert.equal((await snap(p)).frictionTally.tool.net,-4);await p.locator('#friction-answer-tool').click();await p.locator('#friction-glass').click();await p.locator('#friction-predict-cloth').click();for(let n=0;n<4;n++){await p.locator('#friction-rub-key').click();await p.waitForTimeout(900);}await p.locator('#friction-answer-cloth').click();assert.equal((await snap(p)).frictionDone.length,2);await p.locator('#game').screenshot({path:path.join(out,'game-friction.png')});await p.locator('#friction-leave').click();
await go(p,'balloon');await p.getByRole('button',{name:'仍是中性',exact:true}).click();await p.getByRole('button',{name:'摩擦衣物',exact:true}).click();await p.getByRole('button',{name:'近',exact:true}).click();assert.equal((await snap(p)).inquiry.boardQ,0);await p.getByRole('button',{name:'黑板仍中性，近端極化吸引'}).click();await p.waitForTimeout(1200);await p.locator('#game').screenshot({path:path.join(out,'game-balloon.png')});await p.locator('#inquiry-leave').click();
await go(p,'induction');await p.getByRole('button',{name:'正電',exact:true}).click();await p.getByRole('button',{name:'靠近棒',exact:true}).click();await p.getByRole('button',{name:'接地',exact:true}).click();assert.equal((await snap(p)).inquiry.electrons,2);await p.getByRole('button',{name:'斷開接地',exact:true}).click();await p.getByRole('button',{name:'移開棒',exact:true}).click();await p.getByRole('button',{name:'解釋：留下相反電荷'}).click();await p.locator('#game').screenshot({path:path.join(out,'game-induction.png')});await p.locator('#inquiry-leave').click();
await go(p,'contact');await p.getByRole('button',{name:'每球 −4',exact:true}).click();await p.getByRole('button',{name:'接觸兩球',exact:true}).click();await p.waitForTimeout(1250);assert.equal((await snap(p)).inquiry.b,-4);await p.getByRole('button',{name:'分開兩球',exact:true}).click();assert.equal((await snap(p)).inquiry.a,-4);await p.locator('#game').screenshot({path:path.join(out,'game-contact.png')});await p.locator('#inquiry-leave').click();
await go(p,'leyden');await p.getByRole('button',{name:'看剖面',exact:true}).click();assert.ok((await snap(p)).leydenParts.some(x=>x.name==='InnerFoilCutaway'&&x.visible));assert.equal((await snap(p)).leydenParts.find(x=>x.name==='GlassFull').visible,false);await p.locator('#game').screenshot({path:path.join(out,'game-leyden.png')});await p.getByRole('button',{name:'拆解三層',exact:true}).click();await p.locator('#game').screenshot({path:path.join(out,'game-leyden-exploded.png')});await p.locator('#inquiry-leave').click();
await go(p,'vdg');assert.equal((await snap(p)).observationOpen,true);await p.locator('#foyer-watch').click();await p.keyboard.down('q');await p.waitForTimeout(300);await p.keyboard.up('q');assert.ok((await snap(p)).yaw>.2);await p.reload();await p.waitForFunction(()=>window.labGame?.snapshot().environmentStatus==='ready');assert.deepEqual((await snap(p)).completed,[1,2]);
for(const [name,viewport] of [['iphone',{width:844,height:390}],['ipad',{width:1366,height:1024}]]){const m=await browser.newPage({viewport,hasTouch:true,isMobile:name==='iphone',deviceScaleFactor:2});m.on('pageerror',e=>errors.push(e.message));await m.goto(url);await m.waitForFunction(()=>window.labGame?.snapshot().environmentStatus==='ready');await inside(m,['#joystick','#interact','#look-left','#look-right']);const start=(await snap(m)).position;await steer(m);assert.ok((await snap(m)).position[0]>start[0]+.3,'walking joystick moves viewpoint');await m.locator('#game').screenshot({path:path.join(out,`${name}-entry.png`)});await go(m,'scope');await inside(m,['#joystick','#bench-ground','#bench-leave','#bench-rod-positive']);await steer(m);assert.ok((await snap(m)).bench.dist>12,'same joystick adjusts rod');await m.locator('#game').screenshot({path:path.join(out,`${name}-scope.png`)});await m.locator('#bench-leave').tap();await go(m,'leyden');await m.getByRole('button',{name:'看剖面',exact:true}).tap();await inside(m,['#inquiry-leave','#inquiry-actions']);await m.locator('#game').screenshot({path:path.join(out,`${name}-leyden.png`)});await m.locator('#inquiry-leave').tap();const rect=await m.locator('#world').boundingBox();await m.mouse.move(rect.x+rect.width*.6,rect.y+rect.height*.45);await m.mouse.down();await m.mouse.move(rect.x+rect.width*.6+40,rect.y+rect.height+500,{steps:6});await m.mouse.up();assert.ok(Math.abs((await snap(m)).pitch)<=.65,'pitch is clamped');await m.setViewportSize({width:390,height:844});assert.equal(await m.locator('.portrait-note').isVisible(),true);await m.close();}
const broken=await browser.newPage();await broken.route('**/electricity-gallery.glb*',route=>route.fulfill({status:404,body:'not found'}));await broken.goto(url);await broken.waitForFunction(()=>window.labGame?.snapshot().environmentStatus==='failed');assert.equal(await broken.getByRole('button',{name:'重新載入',exact:true}).isVisible(),true);await broken.close();assert.deepEqual(errors,[]);console.log('PASS: all seven opt-in stations reachable; first-person, charge conservation/order, real animation pixel diff, preserved save/XP, no character download, 16:9 desktop/iPhone/iPad layouts.');
}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
